import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { cn } from '@/lib/utils'

// Documentation on the ClerkProvider: https://clerk.com/docs/components/clerk-provider
// Documentation on the ThemeProvider: https://www.npmjs.com/package/next-themes and https://ui.shadcn.com/docs/dark-mode/next
// Documentation on the cn function (twMerge): https://www.npmjs.com/package/tailwind-merge

// Global font settings
const font = Open_Sans({ subsets: ['latin'] })

// Title and description
export const metadata: Metadata = {
  title: 'Team Chat Aplication',
  description: 'Generated by create next app',
}

// 'children' is everything this layout has effect on
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // The ClerkProvider wraps the application to provide active session and user context to Clerk's hooks and other components.
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider>
        <body className={cn(
            // The 'cn' function aka 'twMerge' is from 'tailwind-merge' package. Still don't know what it does
            font.className,
            "bg-white dark:bg-[#313338]"
          )}>
          <ThemeProvider
          // The 'ThemeProvider' comes from the 'next-themes' package. Used to switch between light and dark themes
            attribute='class'
            defaultTheme='dark'
            enableSystem={false}
            storageKey='discord-theme'
          >
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  )
}
